image: devnull-tools/maven

stages:
  - build
  - release

mvn:package:
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
      - target/*
  script:
    - mvn package

mvn:publish:sonatype:
  stage: release
  script:
    - mvn -P sign,public clean deploy
  dependencies:
    - mvn:package
  only:
    - tags

mvn:publish:internal:
  stage: release
  script:
    - mvn -P private clean deploy
  dependencies:
    - mvn:package
  only:
    - tags
    - /^release-.*$/
